# Additional Zabbix Server configurations
# This file is loaded from /etc/zabbix/zabbix_server_extra.conf

# Log File size in MB (0 to disable)
LogFileSize=50

# How long we wait for agent, SNMP or SSH response (1-30 seconds)
Timeout=10

# Housekeeping configuration
# Housekeeping is disabled in database because we use TimescaleDB partitioning,
# but we keep general housekeeper configuration here.
HousekeepingFrequency=1
MaxHousekeeperDelete=5000
