all:
  children:
    monitoring_servers:
      hosts:
        mon-primary:
          ansible_host: 10.0.100.10
        mon-standby:
          ansible_host: 10.0.100.11
    
    linux_servers:
      children:
        app_servers:
          hosts:
            app-node-01:
              ansible_host: 10.0.10.21
            app-node-02:
              ansible_host: 10.0.10.22
        db_servers:
          hosts:
            db-mysql-01:
              ansible_host: 10.0.20.31
              zabbix_agent_plugins: [mysql]
            db-redis-01:
              ansible_host: 10.0.20.32
              zabbix_agent_plugins: [redis]
        mq_servers:
          hosts:
            mq-rabbitmq-01:
              ansible_host: 10.0.20.41
              zabbix_agent_plugins: [rabbitmq]
        web_servers:
          hosts:
            web-nginx-01:
              ansible_host: 10.0.10.11
              zabbix_agent_plugins: [nginx]

    windows_servers:
      hosts:
        win-ad-01:
          ansible_host: 10.0.30.51
          ansible_connection: winrm
          ansible_winrm_server_cert_validation: ignore

    network_devices:
      hosts:
        core-switch-01:
          ansible_host: 10.0.1.2
          snmp_version: v2c
        edge-router-01:
          ansible_host: 10.0.1.1
          snmp_version: v3
